

services:
  db:
    image: postgres:16
    container_name: balconygreen-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ../../
      dockerfile: src/balconygreen/backend/Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
   

  frontend:
    environment:
    - BACKEND_URL=http://backend:8000
    build:
      context: ../../
      dockerfile: src/balconygreen/frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "8501:8501"

  worker:
    build:
      context: ../../
      dockerfile: src/balconygreen/sensors/Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    restart: unless-stopped

volumes:
  postgres_data:
