[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; ---- Build flags (empty for testing, use Config.h) ----
build_flags = 

; ---- Libraries ----
lib_deps =
    bblanchon/ArduinoJson@^7.4.3
    adafruit/DHT sensor library@^1.4.7
    adafruit/Adafruit Unified Sensor@^1.1.15
    milesburton/DallasTemperature
    paulstoffregen/OneWire
   
